### ISSUE TITLE
Error dialogs are unusable on macOS 11

### ISSUE THREAD

**Issue by agatti** [koxudaxi/poetry-pycharm-plugin#223] opened 2021-05-15 13:10 UTC
**Describe the bug**

First off, I'm not sure whether this is a problem specific to the plugin or to PyCharm itself.  Feel free to close this as invalid right away if it's the latter case.

Anyway, the poetry lock/update/upgrade error dialog is unusable.  Text cannot be copied from the dialog, all text is wrapped and centred, and things are so narrow that it is actually kind of difficult to figure out what's going on (remember, cannot even copy and paste the content elsewhere to read it properly).

**To Reproduce**

1. Edit pyproject.toml in the currently loaded project to add an unknown dependency or an invalid version.
2. Let the plugin update the project (either lock or update, doesn't matter).
3. Wait for the error dialog to show up.

**Expected behavior**

A more usable error dialog, I guess - something close to what it used to be in macOS 10.15.  I am not sure whether this can be easily achieved by using a different dialog class in the plugin or not, or if a whole new modal dialog should be designed and implemented instead...

**Screenshots**

<img width="266" alt="Screenshot 2021-05-15 at 15 01 00" src="https://user-images.githubusercontent.com/235740/118362262-232c7900-b58f-11eb-8537-b6a6ab3ab03e.png">

**Environments:**
 - IDE: PyCharm Professional 2021.1.1
 - OS: macOS 11.3.1
 - Poetry Version 1.1.6
 - Plugin version 1.1.3

**Comment by agatti** [comment] 2021-05-15 13:19
For comparison, when performing poetry project updates outside PyCharm and then letting it install the dependencies from the updated project using the top banner on a project file - this one for clarity:


<img width="1089" alt="Screenshot 2021-05-15 at 15 18 25" src="https://user-images.githubusercontent.com/235740/118362690-d77acf00-b590-11eb-848d-c41099028564.png">

the error looks like this:

<img width="858" alt="Screenshot 2021-05-15 at 15 16 27" src="https://user-images.githubusercontent.com/235740/118362665-bdd98780-b590-11eb-9436-9978af48e852.png">

which is arguably more usable than what I'd get when updating the project from the plugin itself.

**Comment by koxudaxi** [comment] 2021-05-16 09:40
Thank you for creating this issue.

I can't reproduce this problem. :cry: 
Because I can't update my macOS.

I want to hear some information to resolve this information.

**Comment by agatti** [comment] 2021-05-16 12:52
Well, PyCharm shows that dialog from here: https://github.com/JetBrains/intellij-community/blob/c5bb04fa149441b0f07472ba9e116d87c9577fc9/python/src/com/jetbrains/python/packaging/PyPackageManagerUI.java#L61 - I guess `ProgressManager` shows the second dialog in case of an exception being thrown and fetching the information needed to fill it from the `InstallTask` static class in the same file.  

Maybe the plugin could use the same mechanism to trigger a project update/upgrade when `pyproject.toml` changes?  Using `Messages.showErrorDialog` for large amount of (formatted) text is not really the best choice on macOS 11, sadly.

**Comment by koxudaxi** [comment] 2021-05-16 13:45
@agatti 
Thank you for giving great hint.
The poetry plugin was created from Pipenv integration in PyCharm.
I checked the code of Pipenv. 
https://github.com/JetBrains/intellij-community/blob/3661d0cc581bb4c21c0b85f0b599821d312c4ce7/python/src/com/jetbrains/python/sdk/pipenv/pipenv.kt#L387
The code was changed.
I will fix the code the same as the code of Pipenv.
![Screenshot from 2021-05-16 22-39-19](https://user-images.githubusercontent.com/630670/118399421-0760ca00-b698-11eb-8e6e-131b88519ff0.png)

**Comment by koxudaxi** [comment] 2021-05-16 17:13
@agatti 
I have sent a new version to Jetbrains Market.
You can install the new version after they will approve the plugin within 2-days.

But, you can download it following this link.
https://github.com/koxudaxi/poetry-pycharm-plugin/releases/tag/1.1.4

**Comment by agatti** [comment] 2021-05-17 12:45
@koxudaxi I just got the new version through JetBrains updates - works a treat, thanks a lot!

**Comment by koxudaxi** [comment] 2021-05-17 13:29
Thank you for your response.
I closed this issue.

**Closed by koxudaxi** 2021-05-17 13:29 UTC
Labels: help wanted
